data_dir: /hdd/cs388/stocknet_dataset
# price_shifts_bins: [-4,-2,-1,-0.5,0.5,1,2,4]
price_shifts_bins: [-0.5,0.5]
price_encode_lens: 5
tweet_encode_lens: 5
glove_path: glove/glove.twitter.27B.25d.txt
lr: 1e-3
batch_size: 1
weight_decay: 1e-2
model: tweet_price_sa
optim: adamw
dropout: 0.2
tweet_hidden_dim: 16
price_hidden_dim: 16
hidden_dim: 32
num_tweet_rnn_layers: 1
num_price_rnn_layers: 1
max_num_tweet: 8
